export const ERROR = {
    INVALID_TOKEN: "INVALID_TOKEN",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    SERVER_ERROR: "SERVER_ERROR",
    PERMISSION_DENIED: "PERMISSION_DENIED",
};