export const ERROR = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",
    ACTIVATION_EXPIRED: "ACTIVATION_EXPIRED",
    INVALID_TOKEN: "INVALID_TOKEN",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    SERVER_ERROR: "SERVER_ERROR"
};